### ISSUE TITLE
'NoneType' object has no attribute 'r0'

### ISSUE THREAD

**Issue by sagreus** [cta-sst-1m/digicampipe#106]
Running pipeline_crab.py, e.g., `./pipeline_crab.py --baseline_path=./dark.npz --outfile_path=./hillas_output.txt ./digicampipe/tests/resources/example_100_evts.000.fits.fz --display`

Produces the following error:
File "./pipeline_crab.py", line 158, in 
main(args)
File "./pipeline_crab.py", line 147, in main
display.draw()
File "/home/paco/CTA/ctasoft2/src/digicamviewer/digicamviewer/viewer.py", line 160, in draw
self.next()
File "/home/paco/CTA/ctasoft2/src/digicamviewer/digicamviewer/viewer.py", line 121, in next
telescope_id = event.r0.tels_with_data[0]
AttributeError: 'NoneType' object has no attribute 'r0'

**Comment by dneise** [comment]
Thanks for reporting. I am having a look

**Comment by yrenier** [comment]
Just a hint, @calispac may confirm.
one step of pipeline_crab.py is to calculate the baseline based on the past `n_bins` clocked triggers.
It means the baseline need at least `n_bins` clocked triggers to be calculated.
A further step is to remove all event without baseline ( with `filter_missing_baseline` function).
So using an example file with 100 event and keeping n_bins to the default value cannot work as no event pass the filter.
Try with a real data file or to lower `n_bins` to a much smaller value such as 10 (supposing there are clocked trigger event in the example file).

**Comment by sagreus** [comment]
Thanks @yrenier I had tried also 2-3 runs with the same results. But it seems that increasing the number of files (or picking an appropriate Crab data file) indeed solves the problem. 
So you can close this issue.
Sorry for the noise.

**Comment by dneise** [comment]
> Sorry for the noise.

I think this was no noise. Other users might have the same problem and the remark by @yrenier  might help them as well. 

Also we might be able to improve error messages, so that people understand better where a problem comes from. 

So thanks for reporting.
