### ISSUE TITLE
event_stream() got an unexpected keyword argument 'file_list'

### ISSUE THREAD

**Issue by sagreus** [cta-sst-1m/digicampipe#127]
I am getting this error in some of the example scripts. It seems like an easy fix, since I think it comes from the change in digicampipe/io/event_stream.py:
https://github.com/cta-sst-1m/digicampipe/commit/d79a296f56f55de6c0b96fc14c33a568a8ec52a8

**Comment by dneise** [comment]
Oh yes, that keyword changed at some point. Would you like to fix it?
I propose to not use any keyword for the 1st argument of event_source, as it is done e.g. here:
https://github.com/cta-sst-1m/digicampipe/blob/b21e1a1d10dd28cb828f25653921377bb81a6ce2/baseline_stability.py#L19-L21

**Comment by dneise** [comment]
So in case we change the keyword in the future from `file_list` to simply `files` then there is not so much to change elsewhere...

**Comment by sagreus** [comment]
Not using any keyword also sounds good to me. We may want to tweak the example scripts so nobody runs into this later.

**Comment by dneise** [comment]
yes exactly .. would you like to repair the examples? or should I do it

**Comment by dneise** [comment]
miss-click

**Comment by sagreus** [comment]
I can do it myself, so I can get more familiar with github.

**Comment by sagreus** [comment]
Done, but I got this error when doing 'git push': (maybe I do not have the rights to commit changes?)
remote: Resolving deltas: 100% (10/10), completed with 9 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To https://github.com/cta-sst-1m/digicampipe
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cta-sst-1m/digicampipe'

**Comment by dneise** [comment]
Nobody has the rights to push into the master. We are using a workflow sometimes known as the [github workflow](https://guides.github.com/introduction/flow/)

please open a pull request so others can review the changes before merging them into the master.

**Comment by sagreus** [comment]
Done! Thanks @dneise

**Comment by dneise** [comment]
No thank you

**Comment by sagreus** [comment]
I think I can close this now.
