### ISSUE TITLE
tels_with_data - stuff

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#128]
I see this a lot .. everywhere in our code it repeats itself:
```python
        for telescope_id in event.r0.tels_with_data:
```

I think in some cases this code would break horribly if there were really more than **one** telelscope in the event_stream. I can give examples...

So not only is this repeating "for-loop which is not really a for-loop" ugly ... it is also dangerous. 

I was wondering if we have to do something about it now ... or if we wait until it breaks and jumps us in the face.

So my understanding is **our zfits files** always contain exactly one telescope (up to now).
What about the hessio and hdf5 file? I assume @calispac knows about the hdf5 and @moderski knows about the hessio files, right?

Maybe they could comment.

**Comment by moderski** [comment]
hessio file, as output from sim_telarray is concerned, may contain data for all the telescopes in the array.
In principle the "event" should contain the data from all the telescopes which participated in that event, isn't it?

**Comment by calispac** [comment]
I also think we should keep the multi-telescope feature even if we have 1 at the moment. However I was wondering is one could do something like this:

```python
for r0_camera in r0_array:
    telescope_id = r0_camera.id
    camera_event = r0_camera.event
```

So the telescope_id is associated to the `CameraContainer()`

in that case if you want to access the list_of_telescopes that triggered this event you have to do:

```python
tels_with_data = [r0_camera.id for r0_camera in r0_array]
```

**Comment by dneise** [comment]
As I said ... there is currently code in this repo, which will break horribly, when we have more than one telescope. By breaking horribly I mean, it will run ... and not throw an exception, but it will create totally wrong results.

I like much better to have software which clearly works for one telescope (e.g. works on the camera server) and clearly breaks for multiple telescopes ... than a software that *seems to work for multiple telescopes as well* but in fact only creates rubbish.

**Comment by moderski** [comment]
I agree with @dneise - especially after watching the presentation he recommended somewhere, it was about an overuse of python classes, but there was a statement there that one should not "anticipate" the future in the code, but rather write what is right for the present and only then work on the emerging necessities.
But there may be an issue about compatibility with ctapipe ...

**Comment by dneise** [comment]
> But there may be an issue about compatibility with ctapipe ... 

yes there will be.

**Comment by dneise** [comment]
This one? 
https://www.youtube.com/watch?v=o9pEzgHorH0

Always love to watch it again :-D

**Comment by dneise** [comment]
But I should also restrain myself here. Etienne said something somewhere else which is very true. 

We should not try to find the best design .. but we should create what works for us.

So at the moment ... it works as it is. And we have no real urge to touch it ... so we should maybe not touch it.But we also should maybe not go to great lengths and try to write code that works for multiple telescopes today. 

So ... I am a bit ashamed here  for wasting your time with this issue and will close it...
