### ISSUE TITLE
trigger_control.py does not work

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#132]
When trying to execute trigger_control.py I get a

    ModuleNotFoundError: No module named 'utils.histogram'

from here:
https://github.com/cta-sst-1m/digicampipe/blob/9ce56785130d4a521789f526f7f635b9f483bcb7/trigger_control.py#L10

I do not understand how this import can ever have worked.... I think we should remove stuff from the master, which does not work.

**Comment by calispac** [comment]
Yes remove it sorry. This was a package I created thanks it ended up into the master by accident

**Comment by dneise** [comment]
perfect thx.

**Comment by dneise** [comment]
will be fixed in #134
