### ISSUE TITLE
strange pixels in crab run

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#138]
I was looking at some of the runs from the crab measurement of last year.
I think I remember somebody told me there was an issue with part of the camera back then.

I think there are actually two issues:
 
![2018-02-26-145913_1920x1080_scrot](https://user-images.githubusercontent.com/8200858/36674196-a3fc7774-1b05-11e8-9bad-59744ae8bf86.png)

So there is this `group_A` of 48-pixels on the upper left side:
```python
group_A = array([
       1085, 1117, 1118, 1119, 1120, 1146, 1147, 1148, 1149, 1150, 1151,
       1152, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181,
       1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206,
       1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1239, 1240, 1241,
       1242, 1243, 1256, 1257])
```

`group_A` seems to be totally unusable. Is that correct?

----

And then there is a smaller `group_B`: 
```python
group_B = np.array([ 896,  930,  931,  932,  966,  967,  968, 1002, 1003, 1004, 1038,
       1039])
```
which seems to be usable, but just have a higher baseline. Is that correct?

----

Is there already a naming scheme for these pixels? Do we call them somehow? Is there an agreed way to treat these pixels? Should all be excluded from further analysis or should `group_B` be treated normal? just subtract the baseline and be done with it?

**Comment by calispac** [comment]
Basically (to keep it simple, even I don't fully remember)
-  group_A is a FADC board that did not initialize 
- group_B module that is broken (replaced recently)

group_B and group_A are not usable. 
In the analysis the values for those pixels where set to zero.

Concerning naming of lets say "pixel_status" it is still to be defined. Also we don't yet know how to detect the issue expect "by eye".

So for now I would say naming goes: 

1. Awake
2. Sleeping
3. Dead

:smile:

**Comment by dneise** [comment]
Thanks .. I would close this, but maybe we want to collect something like this ... in some kind of docu maybe... dunno

**Comment by moderski** [comment]
Github has a "wiki" feature which may be used for more permanent storage of the information.

**Comment by dneise** [comment]
Ah right ... I hardly used the github wikis ever ... should we try to use it? Do you think it is worth a try?
(I fear there is a chance for just-another-place-for-docu .. and so ultimately chaos.)

**Comment by moderski** [comment]
The Wiki is already there, and there is no other place for documenting the issues with the code development (except the Issues themselves, but they are practically gone once closed). We may give it a try. Treat the wiki as a notebook - no need to structure the staff too much at the beginning.
