### ISSUE TITLE
duplicate: extract_charge()

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#144]
There are two functions with the same name in different modules, which have the same parameters and seem to do the same, or nearly the same.

https://github.com/cta-sst-1m/digicampipe/blob/a7d1f07ab606bf6cce45dc437da39eb851e7549b/digicampipe/utils/utils.py#L27-L48

and 

https://github.com/cta-sst-1m/digicampipe/blob/a7d1f07ab606bf6cce45dc437da39eb851e7549b/digicampipe/instrument/camera.py#L132-L154

I think we should check if they are identical, and if so remove one of them.
If they are not identical but different flavors, I think they should live in the same module but have different names, that underline their differences.

**Comment by calispac** [comment]
See answer in #145
