### ISSUE TITLE
duplicate?: gain_drop()

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#145]
Similar to #144 I've run into another duplicate, I think:

Here is the 1st:

https://github.com/cta-sst-1m/digicampipe/blob/a7d1f07ab606bf6cce45dc437da39eb851e7549b/digicampipe/instrument/camera.py#L100-L102

Here is the 2nd:

https://github.com/cta-sst-1m/digicampipe/blob/a7d1f07ab606bf6cce45dc437da39eb851e7549b/digicampipe/utils/calib.py#L32-L38

----

These functions are so short, that I can immediately see they do exactly the same, so there is not much harm they can do ... but still this is a duplication, and we should remove one of them.

**Comment by calispac** [comment]
Thank you for pointing that out. The first implementation (in `instruments.camera`) was an attempt to create a sort of `Processor` for the calibration. Where you would init it before looping over the pipeline and it would contain all calibration steps. 
However I think now that this approach is deprecated. Let's keep it simple with functions. 
So I think we can remove what is duplicated in `digicampipe.instrument.camera`. 
I will write a PR for that.
