### ISSUE TITLE
Pytest fail (missing pytest-benchmark?)

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/digicampipe#148]
I made a fresh install of digicampipe followin the README. 

Everything worked except when running the `pytest` command.

```bash
cyril@ctaanalysis:~/ctasoft/digicampipe$ pytest
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --benchmark-skip
  inifile: /home/cyril/ctasoft/digicampipe/pytest.ini
  rootdir: /home/cyril/ctasoft/digicampipe
```

Just installing `pytest-benchmark` solved the issue:

```bash
(digicampipe) cyril@ctaanalysis:~/ctasoft/digicampipe$ pip install pytest-benchmark
```

I am just wondering how did Travis not have this issue? 
Anyhow I believe one should add this :  
`conda install -c conda-forge pytest-benchmark`

to the `environement.yml`

**Comment by calispac** [comment]
Ok seems that it is there already....

**Comment by dneise** [comment]
Yes the entry seems to be here (current master):
https://github.com/cta-sst-1m/digicampipe/blob/a7d1f07ab606bf6cce45dc437da39eb851e7549b/environment.yml#L88-L89

So should we close this?

**Comment by calispac** [comment]
Yes sorry for the noise...
