### ISSUE TITLE
cron build failed

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#159]
First of all! Awesome! we have this cron-stuff :-D I did not know that @calispac really switched this on. I think it is great!

---

However: Currently the travis cron build fails.

See e.g. here:
https://travis-ci.org/cta-sst-1m/digicampipe/builds/352265351

The reason seems to be somewhere in when it tries to install: CTS:

```
Obtaining CTS from git+https://github.com/cta-sst-1m/CTS.git#egg=CTS (from -r requirements.txt (line 5)
```

Oh .. I should have better openend the issue there.

**Comment by calispac** [comment]
Some fixes were done on CTS side. let's see how it goes. I restarted the cron job

**Comment by dneise** [comment]
Awesome job, thanks a lot
