### ISSUE TITLE
issues with digicam-view and digicam-mpe

### ISSUE THREAD

**Issue by abarbano** [cta-sst-1m/digicampipe#210]
Hi,

when launching digicam-view and digicam-mpe with the following input values I get some errors.
Does any of you have an hint? 
Thanks a lot.

cheers, Anastasia

```
(digicampipe) abarbano@abarbano-XPS13:~/work/digicampipe$ digicam-mpe -c  ../../../digicampipeTests/  /mnt/ctauser/SST1M_01_20180523_106.fits.fz
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/matplotlib/__init__.py:908: MatplotlibDeprecationWarning: The backend.qt5 rcParam was deprecated in version 2.2.  In order to force the use of a specific Qt binding, either import that binding first, or set the QT_API environment variable.
  mplDeprecation)
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/matplotlib/__init__.py:908: MatplotlibDeprecationWarning: The backend.qt5 rcParam was deprecated in version 2.2.  In order to force the use of a specific Qt binding, either import that binding first, or set the QT_API environment variable.
  mplDeprecation)
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/abarbano/anaconda3/envs/digicampipe/bin/digicam-mpe", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-mpe')()
  File "/home/abarbano/work/digicampipe/digicampipe/scripts/mpe.py", line 124, in entry
    raise IOError('Path for output does not exists \n')
OSError: Path for output does not exists 
```

```
digicam-view /mnt/ctauser/SST1M_01_20180523_106.fits.fz
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:matplotlib.legend:No handles with labels found to put in legend. 
```

**Comment by calispac** [comment]
1.  The error says `OSError: Path for output does not exists ` which means that the path `../../../digicampipeTests/` does not exists on your machine. 
Try : `ls ../../../digicampipeTests/`
2. Do you get the viewer ? because these are not errors but a warnings.

**Comment by dneise** [comment]
When I execute `digicam-view` on this file I get this output:

![2018-05-30-144134_1920x1080_scrot](https://user-images.githubusercontent.com/8200858/40720619-a17a3e7c-6417-11e8-9d24-e20dde22096e.png)

```
(digicampipe) dneise@lair:~/sst_new/pdp/2018/05/23$ digicam-view SST1M_01_20180523_106.fits.fz 
/home/dneise/anaconda3-5.1.0/envs/digicampipe/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:matplotlib.legend:No handles with labels found to put in legend.
Events:   0%|                                                                                                             | 0/8606 [00:00<?, ?it/s]/home/dneise/anaconda3-5.1.0/envs/digicampipe/lib/python3.6/site-packages/protozfits/digicam.py:85: UserWarning: trigger_output_patch7 does not exist: --> nan
  warnings.warn('trigger_output_patch7 does not exist: --> nan')
/home/dneise/anaconda3-5.1.0/envs/digicampipe/lib/python3.6/site-packages/protozfits/digicam.py:93: UserWarning: trigger_output_patch19 does not exist: --> nan
  warnings.warn('trigger_output_patch19 does not exist: --> nan')
/home/dneise/anaconda3-5.1.0/envs/digicampipe/lib/python3.6/site-packages/protozfits/digicam.py:101: UserWarning: trigger_input_traces does not exist: --> nan
  warnings.warn('trigger_input_traces does not exist: --> nan')
```

**Comment by abarbano** [comment]
Hi,
I tried with absolute path 
digicam-mpe -c -o /home/abarbano/work/digicampipeTests/ -i /mnt/ctauser/SST1M_01/SST1M_01_20180523_106.fits.fz

so to avoid errors, an indeed the problem persists:
TypeError: stat: can't specify None for path argument

No, I do have the GUI.

Anastasia

**Comment by calispac** [comment]
Please put the full error because I cannot tell what is causing the `TypeError`

**Comment by abarbano** [comment]
Sure, sorry, here it is:
(digicampipe) abarbano@abarbano-XPS13:~/work/digicampipe/digicampipe/scripts$ digicam-mpe -c -o /home/abarbano/work/digicampipeTests/ -i /mnt/ctauser/SST1M_01/SST1M_01_20180523_106.fits.fz
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/abarbano/anaconda3/envs/digicampipe/bin/digicam-mpe", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-mpe')()
  File "/home/abarbano/work/digicampipe/digicampipe/scripts/mpe.py", line 122, in entry
    if not os.path.exists(output_path):
  File "/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument

**Comment by calispac** [comment]
Now without the `-o` and `-i`

```
digicam-mpe -c -o /home/abarbano/work/digicampipeTests/ -i /mnt/ctauser/SST1M_01/SST1M_01_20180523_106.fits.fz
```

**Comment by abarbano** [comment]
Now it says: 

(digicampipe) abarbano@abarbano-XPS13:~/work/digicampipe/digicampipe/scripts$ digicam-mpe -c /home/abarbano/work/digicampipeTests/ /mnt/ctauser/SST1M_01/SST1M_01_20180523_106.fits.fz
/home/abarbano/anaconda3/envs/digicampipe/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/abarbano/anaconda3/envs/digicampipe/bin/digicam-mpe", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-mpe')()
  File "/home/abarbano/work/digicampipe/digicampipe/scripts/mpe.py", line 130, in entry
    n_samples = int(args['--n_samples'])  # TODO access this in a better way !
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Looks like it complains that I do not set the n_samples, so the error related to -c/-i is not there anymore..

**Comment by calispac** [comment]
Ok now my bad... this argument is required for the moment. Look how many samples a waveform has (should be 50 in your case). Then 

```
digicam-mpe -c --n_samples=50 /home/abarbano/work/digicampipeTests/ /mnt/ctauser/SST1M_01/SST1M_01_20180523_106.fits.fz
```

**Comment by abarbano** [comment]
OK, if I set --n_samples and --ac_levels now digicam-mpe works!
As for the digicam-view, I do not know.. but ok, it is not very urgent now..
Thanks!

Anastasia

**Comment by calispac** [comment]
Anyway you are probably using the wrong script for what you need (this is an analysis script reconstructed the multiple photo electron spectrum. Thus you need a file with light and you need to give the ac_levels as well). For the viewer please update your first post with the full error message.

**Comment by dneise** [comment]
I think, this can be closed now
