### ISSUE TITLE
DigiCam baseline new format and reader

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/digicampipe#211]
We recently added to DigiCam better baseline precision. Previously the baseline was encoded in 12bits integers. Now DigiCam returns a value on 16bits with the last 4 bits being the decimal values e.g.

4095.0625 would be : `111111111111 0001`. Without "touching" anything this would be red as 65521. To obtain the correct value we can divide this number by 16. My question here is : 
How can we make sure that such operation is performed only on the correct files ? Is there a way to access in the zfits header the version number of DigiCam ? 

One proposed solution was to rewrite all the baselines in the previous files. 
I suppose the 12bits to 16bits "transform" was done as : `111111111111` --> `0000111111111111`.
And we should rewrite everything as : `111111111111` --> `1111111111110000`

**Comment by dneise** [comment]
Looking for example at this file: `SST1M_01_20180523_106.fits.fz` with protozfits v1.0.2 (renamed `SimpleFile` to `File`)

one can get the table header of the `Events` table like this:

```python
from protozfits import File
f = File('SST1M_01_20180523_106.fits.fz')
print(f.Events.header)
```

In this header one can find the major and minor ACTL version. ( I have removed everything, I thought was not interesting for this question from the header)

```
TFIELDS =                    9 / number of fields in each row                   
EXTNAME = 'Events'             / name of extension table                        
ZNAXIS2 =                 8606 / Number of uncompressed rows                    
RUNTYPE = 'None'               / Type of data in the table                      
PBFHEAD = 'DataModel.CameraEvent' / Written message name                        
CREATOR = 'N4ACTL2IO14ProtobufZOFitsE' / Class that wrote this file             
COMPILED= 'Apr 25 2018 09:28:02' / Compile time                                 
ORIGIN  = 'CTA'                / Institution that wrote the file                
WORKPKG = 'ACTL'               / Workpackage that wrote the file                
TIMESYS = 'UTC'                / Time system                                    
REVISION=                    0 / SVN revision                                   
MAJORV  =                    1 / Major ACTL release                             
MINORV  =                    0 / Minor ACTL release                             
DATE    = '2018-05-23T14:21:39' / File creation date                            
DATEEND = '2018-05-23T14:22:09' / File closing date    
```

**Comment by dneise** [comment]
From this header, I believe we cannot find out the DigiCam version ... unless it might be encoded in the CREATOR class name some how .. there are some numbers in the name, I do not know what they mean.

Or by the time.

**Comment by dneise** [comment]
An additional source of "header-like" information could be the `.head` field which each `CameraEvent` has, reading just the first event from this file and looking at the `.head` field ...

```
event = next(f.Events)
print(event.head)
```
 ... reuslts in:

```
CameraRunHeader(
    telescopeID=-1
    runNumber=0
    dateMJD=0
    timeNanoSec=0
    imgReducMode=<imgReducMode.NO_IMG_REDUC: 0>
    evtsReducMode=<evtsReducMode.NO_EVT_REDUC: 0>
    numTraces=-1
    numGainChannels=-1
    integWindowSize=-1
    integThreshold=-1
    zeroSuppThreshold=-1
    adcs=-1
    triggers=-1
    adcbits=-1
    sumlength=-1
    blprecision=-1
    mastercards=-1
    triggercards=-1
    adccards=-1
    gpss=-1
    telescope_id=0
    cs_serial=''
    run_id=0
    date=0
    num_pixels=0
    num_samples=0
    expected_pixels_id=array([], dtype=float64)
    data_model_version=''
    nectarcam=nectarcam_specific_head(
        idaq_version=''
        camtoactl_version=''
        acquisition_mode=0
        num_modules=0
        expected_modules_id=array([], dtype=float64)
        algorithms=0)
    lstcam=lstcam_specific_head(
        idaq_version=''
        camtoactl_version=''
        num_modules=0
        expected_modules_id=array([], dtype=float64)
        algorithms=0
        pre_proc_algorithms=0))
```

as you see, this is completely empty at the moment.

**Comment by dneise** [comment]
So, since the information seems not to be in stored in the files, I believe I am the wrong person for this question.

**Comment by calispac** [comment]
@Etienne12345 
Do you think rewriting all the files is a good solution for the time being ?

**Comment by dneise** [comment]
Cyril recommended to compare the headers of two files, the one from 28.05. contains the baseline still in 12bit integers, where the one from 01.06. contains the baseline in 16bit fixed-point (12bits for the integer part, 4 bits for the fractional part) format.

Here are the (hopefully relevant) parts of their `File(path).Events.header`:
```
In [13]: File('SST1M_01_20180601_2954.fits.fz').Events.header
Out[13]: 
EXTNAME = 'Events'             / name of extension table                        
ZNAXIS2 =                 8814 / Number of uncompressed rows                    
PBFHEAD = 'DataModel.CameraEvent' / Written message name                        
CREATOR = 'N4ACTL2IO14ProtobufZOFitsE' / Class that wrote this file             
COMPILED= 'Apr 25 2018 09:28:02' / Compile time                                 
ORIGIN  = 'CTA'                / Institution that wrote the file                
WORKPKG = 'ACTL'               / Workpackage that wrote the file                
TIMESYS = 'UTC'                / Time system                                    
REVISION=                    0 / SVN revision                                   
MAJORV  =                    1 / Major ACTL release                             
MINORV  =                    0 / Minor ACTL release                             
DATE    = '2018-06-01T14:40:27' / File creation date                            
DATEEND = '2018-06-01T14:41:27' / File closing date                             
TFORM5  = '1QB'                                                                 
TTYPE5  = 'hiGain_waveforms_baselines'                                          
ZFORM5  = '1296I'                                                               
ZCTYP5  = 'CTA'                / Custom CTA compression                         
TPBID5  = '6.1.5'              / Protobuf ID                                    


In [14]: File('SST1M_01_20180525_154.fits.fz').Events.header
Out[14]: 
EXTNAME = 'Events'             / name of extension table                        
ZNAXIS2 =                 9998 / Number of uncompressed rows                    
PBFHEAD = 'DataModel.CameraEvent' / Written message name                        
CREATOR = 'N4ACTL2IO14ProtobufZOFitsE' / Class that wrote this file             
COMPILED= 'Apr 25 2018 09:28:02' / Compile time                                 
ORIGIN  = 'CTA'                / Institution that wrote the file                
WORKPKG = 'ACTL'               / Workpackage that wrote the file                
TIMESYS = 'UTC'                / Time system                                    
REVISION=                    0 / SVN revision                                   
MAJORV  =                    1 / Major ACTL release                             
MINORV  =                    0 / Minor ACTL release                             
DATE    = '2018-05-25T16:11:45' / File creation date                            
DATEEND = '2018-05-25T16:12:02' / File closing date                             
TFORM5  = '1QB'                                                                 
TTYPE5  = 'hiGain_waveforms_baselines'                                          
ZFORM5  = '1296I'                                                               
ZCTYP5  = 'CTA'                / Custom CTA compression                         
TPBID5  = '6.1.5'              / Protobuf ID                                    
```

We see absolutely nothing has changed in the header of these files. Not even the writer needed to be recompiled, i.e. the compile time is identical.... now after I think about it, this is absolutely logical. The camera still sends the same data .. it just uses more bits.

**Comment by dneise** [comment]
As a kind of emergency measure, I believe we could analyse the distribution of the 4 least significant bits... maybe.

![emergency_find_out_baseline_format](https://user-images.githubusercontent.com/8200858/40925175-5d390508-6819-11e8-8596-f3fd5ceba6d0.png)

here as an example the 4 least significant bits of an old file in blue and the 4 least significant bits of a new file in orange, for the 1st 100 events of a file of pixel 133 .. 

Here the same, using the 6 least significant bits, and of these 6 bits ignore the 2 least significant bits.
so so the `o`s in this number: `xxxx.xxxx.xxoo.ooxx`, (before it was like this: `xxxx.xxxx.xxxx.oooo`)

![emergency_find_out_baseline_format_4bits_after_2lsb](https://user-images.githubusercontent.com/8200858/40925436-fee5e740-6819-11e8-853d-364d756b614c.png)

The effect is still visible, but less pronounced...

If the baseline gets really noisy, this emergency procedure breaks down... but for a few days we might be able to survive like this.

**Comment by Etienne12345** [comment]
Or just look at the max value ? Baselines are around 200, I'd guess always below 2000. 200x16 = 3200. So we could test something like "if the average of the baseline values of the first event is > 2500, then 16 bits".

**Comment by moderski** [comment]
If the 16bit is our target format I think we should really convert old
files to that format and not introduce some checks in the code which will
be never used in the future.

RM

**Comment by dneise** [comment]
Rafal, I believe you are right. At least in the long term. But is it doable? 

I mean, once the files are ingested into the archive, they in principle must never be touched again, right? I do not know if there are formal rules about "repairing files in the archive", but I always got the impression that this archive is not "just a folder" where one can modify the files...

But I don't know. This is something I believe @Etienne12345 can explain best.

**Comment by moderski** [comment]
But we are not in the normal operations mode, yet. If we believe that
during normal operation the format will be 16 bit, we should just convert
and not introduce useless lines of code. In HESS we have had a situation
when after finding a bug in the calibration software all the archival data
were re-calibrated (I am not sure if this actually happened to the raw
data, but some files as old as "from the beginning of time" were affected).

RM
