### ISSUE TITLE
problem of glibc version with the new zfitreader

### ISSUE THREAD

**Issue by yrenier** [cta-sst-1m/digicampipe#215]
On a computer with glibc_2.12 installed, trying to use the zfitreader yileds to:
`File "/home/reniery/anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 6, in <module>`
`    from . import rawzfitsreader`
`ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /home/reniery/anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/rawzfitsreader.cpython-35m-x86_64-linux-gnu.so)`

**Comment by yrenier** [comment]
@dneise do you have the instruction to build the rawzfitsreader library ?

**Comment by ysagon** [comment]
Any news on this? A user of our cluster has the same issue (Centos 6.9).

**Comment by yrenier** [comment]
Hi Yann, I guess I am one of those user :-)
I did not solve this yet. I  will let you know if I find a solution

**Comment by Etienne12345** [comment]
I am in the process of issuing a newer version of this module, only I am waiting for the Git-Master Dominik to validate my stuff. This newer version was compiled on SL6, so the library version should be ok !
Yves you can pull from the branch "version 1.1" already, or wait for the tarball to be ready.

**Comment by Etienne12345** [comment]
Oh and:
@ysagon if you wanna install the lib for Yves in case he does not manage to upgrade to the newer version of the module himself, I fixed this issue on my server running SL6 by installing glibc-2.14.90-14.x86_64.rpm which I placed on my repo here: https://www.isdc.unige.ch/~lyard/repo/
@yrenier If nobody replies to your messages, do not wait 28 days to poke me ;)

**Comment by yrenier** [comment]
@Etienne12345 I will try the new version, thanks !

**Comment by yrenier** [comment]
I made it work with the branch 'working_on_version_1.1' of the protozfitreader, together with the branch 'use_protozfits_v1.0.0' of digicampipe (which despite of his name is now for protozfits_v1.1 apparently).

I discovered that some other package installed by conda were also compiled with uncompatible glibc version, but I could go around that installing all digicampipe requirements with `pip install --user` instead of using conda.

**Comment by yrenier** [comment]
should be fixed by #228 and related protzfit#44
