### ISSUE TITLE
Make this repo part of an organisation?

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#22]
To make collaboration easier, and to allow collaboration even on private repos, which can only be seen by members of the organisation, I propose to shift digicam repos into a github organisation.

One can make a new organisation here:
https://github.com/organizations/new

One can try to request a discount on unlimited private repos for educational purposes here:
https://education.github.com/

We got this discount for the fact orga.

I have just created an organization and invited two people @cocov and @calispac. I do not know the github handles of the other people in SST-1M (which is also something solved by an organisation, since its memberlist can be looked at).

https://github.com/cta-sst-1m

**This is just an example** So you can take a look at it. I can ask github for a discount for private repos for this organisation, and we can have a look if we like it or not. Of course I will transfer ownership to somebody from Geneva or Kraków, dunno. (Many people can be admins of such an orga, but the owner is responsible for paying the bill, if one chooses, to use something that costs money).

Have a look and see if you like it.

**Comment by calispac** [comment]
Can we have a gitter.im linked to the organization repr. ?

**Comment by dneise** [comment]
I have no clue of gitter.

**Comment by dneise** [comment]
Ah yes I was able to *grant*  gitter access to the orga public repos.

following this description (point 2)
https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-


![2017-11-22-102154_1920x1080_scrot](https://user-images.githubusercontent.com/8200858/33119349-ff179b12-cf6e-11e7-97a7-00c0c2233fb6.png)

**Comment by dneise** [comment]
now .. what? is there an automatic room called like our orga in gitter?

**Comment by dneise** [comment]
https://gitter.im/CTA-SST-1M/Lobby#

**Comment by dneise** [comment]
according to this:
https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-communities-and-rooms

One has to make a gitter-community and then link that to the orga, which I think I did.

**Comment by dneise** [comment]
This was a bad idea. I discussed with some people workin on LST code and on ctapipe. 
I understand now, that the idea is that all CTA code is collected in the  https://github.com/cta-observatory organisation.

Accordingly I will delete the https://github.com/cta-sst-1m organisation in an hour.

**Comment by calispac** [comment]
Hi all ! I just want to revive this issue. I am still for an org. repo. It will be simpler for management. Some functionalities of Travis CI requires the owner to login to Travis.

**Comment by dneise** [comment]
Oh I missed this .. 
So I don't mind ... if you want to move to and orga .. let's do it:
https://github.com/cta-sst-1m ...still exits...  3 people are owners and can invite the other people every time.

It is still a on a "free" plan, so no private repos....

**Comment by dneise** [comment]
If the mattermost logbook turns out to be used a lot by people, we can even have a mattermost github integration:
https://github.com/softdevteam/mattermost-github-integration

**Comment by calispac** [comment]
> If the mattermost logbook turns out to be used a lot by people, we can even have a mattermost github integration:
good to know but I think so far we have realized it is not so great...

**Comment by dneise** [comment]
ok .. also fine

**Comment by calispac** [comment]
Ok I will try to transfer ownership to cta-sst-1m org. However I fear it a little bit so I will do it when I have more time in the day ^^. 
I wonder how travis and gh-pages will react.

**Comment by dneise** [comment]
> I wonder how travis and gh-pages will react.

:-D no idea .. 
so yeah ...  take your time ...

**Comment by calispac** [comment]
Transfer is done. Just need to fix the install paths of some other repos see #92
