### ISSUE TITLE
'HillasParametersContainer' object has no attribute 'size'

### ISSUE THREAD

**Issue by jurysek** [cta-sst-1m/digicampipe#220]
I reinstalled digicampipe and if I try to run `simtel_pipeline.py` following error appears:

```
  File "/home/jakub/ctasoft/digicampipe/digicampipe/calib/camera/dl2.py", line 47, in calibrate_to_dl2
    if moments_first.size == 0:
AttributeError: 'HillasParametersContainer' object has no attribute 'size'

```
I think the problem is that ctapipe version which comes with digicampipe installation is from https://github.com/cta-observatory/ctapipe/ and this version is not longer compatible with digicampipe. They stopped using `MomentParameters()` and left `HillasParameterContainer()` only in the ctapipe.image.hillas and it doesn't contain the size attribute anymore.. I think the @calispac 's version at https://github.com/calispac/ctapipe/ would probably still work, but in that case, we should change it in environment.yml file.

**Comment by calispac** [comment]
Thanks for the issue. Actually since we never implemented a test for it we never realized it.
If you could change the code to be ctapipe compatible that would be best. I personally think it is better that we try to keep up with latest changes in ctapipe
