### ISSUE TITLE
Compatibility with ctapipe >= 0.6.0

### ISSUE THREAD

**Issue by yrenier** [cta-sst-1m/digicampipe#230]
I got troubles earlier with the pipeline failing because of the "container" keyword to the ctapipe.image.hillas_parameters has apparently been removed in latest release.
Shall we setup a branch to test against new version of ctapipe ?

**Comment by yrenier** [comment]
#231 experience the issue, so no need of a new branch :-)

**Comment by yrenier** [comment]
I ll wait until it is fixed to close the issue

**Comment by yrenier** [comment]
fixed by https://github.com/cta-sst-1m/digicampipe/pull/231/commits/da9ee709b0655f1fb9989165a506c0ae8e20bfde

**Comment by dneise** [comment]
one question: does our pipeline work with ctapipe < 0.6.0 or not? if it does not work with older versions I think there is no need for this if...else ... we just require the version to be > 0.6 and only keep the else part.

We can require versions in the environment.yml or the setup.py or both.,,

**Comment by yrenier** [comment]
I think it works with some versions < 0.6 (for @calispac for example, correct me if I'm wrong).
There must have been some regression which was fixed since, so with the latest version as installed by default by environment.yml is works.
In those conditions I'm not sure what is best

**Comment by dneise** [comment]
okay .. so we keep it like this for the moment ... but in general I think such if version else stuff should be removed asap ... it just makes the code harder to read. 
And honestly, if ctapipe 0.6 is released ... why should we support old stuff and make our live harder?

**Comment by yrenier** [comment]
I agree with you, I will remove it, but I'm not sure how to impose ctapipe version to be >=0.6 in environment.yml as it loading it directly with git.
I also looked in setup.py and it is not mentioned there.

**Comment by yrenier** [comment]
done, cf https://github.com/cta-sst-1m/digicampipe/pull/231/commits/7d7a37c5341329e51e04abf08360c588eccac59f
