### ISSUE TITLE
changed --output in raw.py

### ISSUE THREAD

**Issue by moderski** [cta-sst-1m/digicampipe#235]
Just a comment: the script raw.py was recently changed by @yrenier and now it does not behave like described in the Wiki about data analysis (--output is now output filename, not a directory with no default raw_histo.pk). This creates unnecessary confusion among data analyzers.
I suggest that the default behavior would be to create raw_histo.pk in the current directory if no --output option is given, while --output could specify a different filename, with or without the full path.

**Comment by yrenier** [comment]
It makes sense, also thanks to remind me to update the wiki :-)

**Comment by yrenier** [comment]
I just updated the wiki, the default value for output is now part of #237
