### ISSUE TITLE
Problem on Baseline in mpe script with toy datas

### ISSUE THREAD

**Issue by ekoume** [cta-sst-1m/digicampipe#265]
If we turn script fmpe on toy datas, we have problem with fill_digicam_baseline and substract baseline functions. So we need to comment thoses lines in mpe.py.

**Comment by calispac** [comment]
The problem is that the Monte-Carlo cannot reproduce the baseline as computed by DigiCam. One solution could be to add an option to subtract or not the baseline by passing an option ``--subtract_baseline`` or pass a file containing the baseline values with ``--baseline``
