### ISSUE TITLE
Wrong exception on invocation of `read_raw_events.py`

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#39]
So I just got my hands on some raw data files and wanted to try `read_raw_events.py`

When I tried this:

    python digicampipe/read_raw_events.py\
         -d /home/dneise/Downloads/SST1M_DATA/ \
         -c /home/dneise/ctasoft/CTS/config/camera_config.cfg

I get this exception:

    TypeError: object of type 'int' has no len()

BUT .. when I read further up, I find this:

    Open has failed. Error: Key 'PBFHEAD' not found. while reading file /home/dneise/Downloads/SST1M_DATA/BASELINE_TEST_0_000.000.fits.fz and table Events

Looking at the filename .. I see, I do not even have that file ... I only have 001 and 060. So I realize, this has something to do with the `-s` and `-e` parameters ... and indeed they are by default set to 0 and 23 respectively. 

The fact, that I as a user have to specify these parameters correctly is totally fine, and that I get an exception, if I do not specify them correctly is also file. Just, it should not be a [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError) not a TypeError

**Comment by Etienne12345** [comment]
Indeed not very nice. This is on my "to fix list" for months now... 
really we should verify that the file exists before attempting to open it with the zfits layers. 
question is: should I update the zfits C++ reader (and return a C++ exception in case of failure ?) or should we rather do it on the python side ? 
Maybe should do it on both sides

**Comment by dneise** [comment]
Works now:
```
python read_raw_events.py -d ../data/ -c./digicampipe/tests/resources/camera_config.cfg
/home/dneise/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:matplotlib.legend:No handles with labels found to put in legend.
/home/dneise/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:1320: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/home/dneise/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py:2022: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "
Traceback (most recent call last):
  File "read_raw_events.py", line 39, in <module>
    display.draw()
  File "/home/dneise/sst/digicamviewer/digicamviewer/viewer.py", line 160, in draw
    self.next()
  File "/home/dneise/sst/digicamviewer/digicamviewer/viewer.py", line 119, in next
    for i, event in zip(range(step), self.event_stream):
  File "/home/dneise/sst/digicampipe/digicampipe/io/event_stream.py", line 22, in event_stream
    for event in data_stream:
  File "/home/dneise/sst/digicampipe/digicampipe/io/zfits.py", line 50, in zfits_event_source
    for event_counter, event in enumerate(ZFile(url)):
  File "/home/dneise/anaconda3/lib/python3.6/site-packages/protozfitsreader/__init__.py", line 168, in __init__
    raise FileNotFoundError(fname)
FileNotFoundError: ../data/BASELINE_TEST_0_000.000.fits.fz
```
