### ISSUE TITLE
first telescope id was 1 now 0

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/digicampipe#56]
Apparently in the recent changes we have in digicampipe telescope id=0 as before it must have been 1.

I realized this with `digicamviewer`.  Anyway I will change the viewer to have by default telescope_id=0 or better force the user to choose the correct telescope id

**Comment by dneise** [comment]
Is this fixed already?

**Comment by calispac** [comment]
No. Sorry did not find the time.

**Comment by dneise** [comment]
Can you write down, how to call the viewer?

**Comment by calispac** [comment]
Here is the init of the viewer. Last commit changed the default value of `telescope_id`

https://github.com/cta-sst-1m/digicamviewer/blob/e0bf38e34a235a7eef230a5f1bbefe89b66960bf/digicamviewer/viewer.py#L14-L16

**Comment by dneise** [comment]
https://github.com/cta-sst-1m/digicamviewer/blob/e0bf38e34a235a7eef230a5f1bbefe89b66960bf/digicamviewer/viewer.py#L14-L16

**Comment by dneise** [comment]
This PR might fix this problem for the moment.

https://github.com/cta-sst-1m/digicamviewer/pull/4
