### ISSUE TITLE
Border computation is broken

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/digicampipe#72]
https://github.com/calispac/digicampipe/blob/39ab15dcd16179489ecf172db17ce73d58dce768/digicampipe/calib/camera/dl1.py#L65

Apparently there is an issue with the computation of border image. It seems that for all images it outputs `True` i.e. that the cleaned image touches the camera border.

I will try to fix this soon. I will also take advantage of this to rewrite this piece of code in a function.

**Comment by dneise** [comment]
I think this will be fixed in #121

**Comment by calispac** [comment]
yep thanks
