### ISSUE TITLE
Error: Table RunHeader could not be found in input file

### ISSUE THREAD

**Issue by sagreus** [cta-sst-1m/digicampipe#93]
I am running into this issue in some of the scripts. For instance when running "dark_evaluation.py" it throws this message:

Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file digicampipe/tests/resources/example_100_evts.000.fits.fz and table RunHeader
/home/paco/CTA/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:185: UserWarning: digicampipe/tests/resources/example_100_evts.000.fits.fz has no RunHeader
  "{} has no RunHeader".format(self.fname))

Maybe it is related with some formatting in "protozfitsreader"? 
I am using a fresh installation of digicampipe.

**Comment by calispac** [comment]
Could you copy the full terminal error ? From which function this is appearing ?

**Comment by Etienne12345** [comment]
AFAIK, there is no such thing as a table "RunHeader" in our raw data files. Maybe you got an old version of the pipeline ?

**Comment by sagreus** [comment]
@calispac Well that was basically it, the full terminal is:

(digicampipe) paco@paco-pc:~/CTA/ctasoft/digicampipe$ ./dark_evaluation.py
0it [00:00, ?it/s]Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file digicampipe/tests/resources/example_100_evts.000.fits.fz and table RunHeader
/home/paco/CTA/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:185: UserWarning: digicampipe/tests/resources/example_100_evts.000.fits.fz has no RunHeader
  "{} has no RunHeader".format(self.fname))
8it [00:01,  7.46it/s]

As for the function is difficult to track as the script finishes properly.

**Comment by Etienne12345** [comment]
Or maybe an old version of the protozfits reader ? I lots track of the current status, but it looks to me that if "RunHeader" shows up in the log, there must be somewhere in the python code where it is asked to open table "RunHeader". Which is wrong obviously (see my previous message).

**Comment by sagreus** [comment]
@Etienne12345 
The error "has no RunHeader".format(self.fname))" is an **exception** that comes directly from:
digicampipe/digicampipe/io/protozfitsreader.py:185
I will try to track it better to see where it asks for "RunHeader"

**Comment by Etienne12345** [comment]
Yes, that's the way it is supposed to be: 
- request "tableName"
- if no table "tableName" in file, then exception

what remains confusing (maybe this is the culprit here) is that the same exception is raised if the requested -file- does not exist. Does file "digicampipe/tests/resources/example_100_evts.000.fits.fz " exists on your system ?

**Comment by sagreus** [comment]
@Etienne12345 
Yes, the file does exist. (Actually, this is the default file pointed by the script which comes by default)
I also tried a different file and I get the same error.

**Comment by dneise** [comment]
This issue is at least part of the reason.

https://github.com/cta-sst-1m/protozfitsreader/issues/8

Gonna fix it in 2..3h

**Comment by dneise** [comment]
And this might also be a reason

https://github.com/cta-sst-1m/protozfitsreader/issues/9

**Comment by dneise** [comment]
Ah thanks for reporting this.

**Comment by dneise** [comment]
Erm one second. I think @sagreus said it further up. The script finishes properly.

There is also no traceback, so there is no exception here. So the protozfitsreader/#8 is probably the only thing here. 

The user was confused by the warning.

**Comment by dneise** [comment]
Ok, after my inconsistent talk of yesterday evening, I reinstalled ctapipe also freshly from scratch 
(a good idea after we moved to the cta-sst-1m orga repo, I guess)

I executed this:

    (digicampipe) dneise@lair:~/ctasoft/digicampipe$ ./dark_evaluation.py 

And got this output:
```
0it [00:00, ?it/s]Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file digicampipe/tests/resources/example_100_evts.000.fits.fz and table RunHeader
/home/dneise/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:185: UserWarning: digicampipe/tests/resources/example_100_evts.000.fits.fz has no RunHeader
  "{} has no RunHeader".format(self.fname))
8it [00:00,  9.14it/s]
```

Very quickly. Then my CPU fan went on and it took a little while (1..3seconds maybe?) until 3 matplotlib windows opened. 

At the same time, I got this additional output, which might be connected to my local matplotlib installation. Not sure yet.
```
/home/dneise/anaconda3/envs/digicampipe/lib/python3.5/site-packages/matplotlib/font_manager.py:1316: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

----

Also the script created two output files as a result. Since we are currently in a git-work-directory, these files can be found e.g. like this:

    git status

output in my case after a fresh installation is:
```
(digicampipe) dneise@lair:~/ctasoft/digicampipe$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bias_curve_dark.npz
	dark.npz

nothing added to commit but untracked files present (use "git add" to track)
```

So question to @sagreus : Do you also get 3 matplotlib windows and these 2 output files?

**Comment by sagreus** [comment]
@dneise 
Yes, exactly the same as you described, except the matplotlib (fontmanager etc.) output which I did not get.

**Comment by dneise** [comment]
>  except the matplotlib (fontmanager etc.) output which I did not get.

Ah I found the problem. It is the `matplotlibrc` file in the digicampipe/ folder. It tries to use some fonts which I have not installed apparently. 

Opening a new issue for this matter.

@sagreus if you like you could review the new PR #96 which is trying to solve this warning.
