### ISSUE TITLE
matplotlibrc

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#97]
There is a `matplotlibrc` file in the digicampipe folder.

This is causing such a warning for me:
```
(digicampipe) dneise@lair:~/ctasoft/digicampipe$ ./dark_evaluation.py 
8it [00:00,  9.04it/s]
/home/dneise/anaconda3/envs/digicampipe/lib/python3.5/site-packages/matplotlib/font_manager.py:1316: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

When for example executing `dark_evaluation.py`.

What is the purpose of this file? For example when I call `dark_evaluation.py`from a different folder, like this:
```
(digicampipe) dneise@lair:~/ctasoft$ digicampipe/dark_evaluation.py 
8it [00:00,  9.03it/s]
```

Then I do not get these warnings, because the `matplotlibrc` is not taken into account. 
If the intention of this `matplotlibrc` file is to ensure that all plots look the same for all users, then I think it failed. 
The result of a program should not change, when called from a different location.

I think one needs to find a proper solution for this.

**Comment by calispac** [comment]
> This is causing such a warning for me

I think we can change the font to DejaVu or require serif to be installed.

> If the intention of this matplotlibrc file is to ensure that all plots look the same for all users, then I think it failed.

Yes it was the goal or at least to provide users with a plot styling if they need it. IWe might want to create a matplotlibrc that would be used for every plot produce with packages inside the orga. I suppose we can create a `utils` repo for this kind of stuffs, containing for instance:

1. matplolibrc file
2. latex_template

Just for info here is the matplotlib config page: https://matplotlib.org/users/customizing.html

**Comment by calispac** [comment]
The file is not part of the project anymore
